### ISSUE TITLE
能否支持 dnspod

### ISSUE THREAD

**Issue by elunez** [danbao/auto-ssl#1]
你好，能否支持dnspod里面的域名

**Comment by danbao** [comment]
@elunez 支持了，
https://github.com/danbao/auto-ssl/blob/main/.github/workflows/dnspod-autossl.yaml
在 secret 里面加上 DP_ID和DP_KEY这两个就可以了，域名写在这里
https://github.com/danbao/auto-ssl/blob/main/dnspod_domains_list.txt
