### ISSUE TITLE
[功能需求] 如果可以使用阿里云相关服务就更好了

### ISSUE THREAD

**Issue by shadowqcom** [danbao/auto-ssl#3]
1、通过阿里云进行dns验证
2、推送证书到阿里云cdn和dcdn

**Comment by danbao** [comment]
@shadowqcom 其实是类似，你只需把 Cloudflare 的那两个变量改成 aliyun 的就可以了
具体参考这里
https://github.com/acmesh-official/acme.sh/wiki/dnsapi
export Ali_Key=""
export Ali_Secret=""

**Comment by shadowqcom** [comment]
> @shadowqcom 其实是类似，你只需把 Cloudflare 的那两个变量改成 aliyun 的就可以了 具体参考这里 https://github.com/acmesh-official/acme.sh/wiki/dnsapi export Ali_Key="" export Ali_Secret=""

明白了，那么接下来只需要搞定怎么推送证书到cnd和dcnd了

**Comment by danbao** [comment]
@shadowqcom 只要有 api 都可以弄，不过这个项目目前不会去弄，你可以改改自己的私有库

**Comment by helloint** [comment]
看起来，主要工作还是后面的证书部署环节，需要编码实现，虽然会有些繁琐，但国内云服务商倒也不多。
而前者，证书申请，其实acme已经封装的差不多了。

**Comment by laboratorys** [comment]
> 看起来，主要工作还是后面的证书部署环节，需要编码实现，虽然会有些繁琐，但国内云服务商倒也不多。 而前者，证书申请，其实acme已经封装的差不多了。

这个貌似部署还是要手动···
